In [1]:
%matplotlib inline
# 内嵌画图，可以省掉plt.show()了

In [2]:
from __future__ import print_function
# 如果某个版本中出现了某个新的功能特性，而且这个特性和当前版本中使用的不兼容，那么我如果想要使用的话就需要从future模块导入
# 在开头加上这句之后，即使在python2.X，使用print就得像python3.X那样加括号使用
import torch

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[8.9082e-39, 1.0194e-38, 9.1837e-39],
        [4.6837e-39, 9.9184e-39, 9.0000e-39],
        [1.0561e-38, 1.0653e-38, 4.1327e-39],
        [8.9082e-39, 9.8265e-39, 9.4592e-39],
        [1.0561e-38, 1.0653e-38, 1.0469e-38]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.0400, 0.0057, 0.4918],
        [0.5339, 0.2269, 0.4939],
        [0.1039, 0.0083, 0.4454],
        [0.5431, 0.3542, 0.3068],
        [0.8445, 0.4177, 0.8832]])


In [5]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5,3,dtype=torch.double) # new_* 方法来创建对象
print(x)

x = torch.rand_like(x,dtype=torch.float) # 覆盖dtype!
print(x) # 对象的size是相同的，只是值和类型发生了变化

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.7169, 0.4841, 0.9988],
        [0.0378, 0.6409, 0.0546],
        [0.0641, 0.9291, 0.5016],
        [0.2986, 0.9322, 0.3842],
        [0.6907, 0.2530, 0.9781]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
y = torch.rand(5,3)
print(x + y)

tensor([[1.3937, 1.4660, 1.7507],
        [0.3443, 1.3641, 0.1677],
        [0.3474, 1.7869, 0.7800],
        [0.9442, 1.2195, 1.1489],
        [1.3853, 0.3768, 1.0244]])


In [10]:
print(torch.add(x,y))

tensor([[1.3937, 1.4660, 1.7507],
        [0.3443, 1.3641, 0.1677],
        [0.3474, 1.7869, 0.7800],
        [0.9442, 1.2195, 1.1489],
        [1.3853, 0.3768, 1.0244]])


In [11]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[1.3937, 1.4660, 1.7507],
        [0.3443, 1.3641, 0.1677],
        [0.3474, 1.7869, 0.7800],
        [0.9442, 1.2195, 1.1489],
        [1.3853, 0.3768, 1.0244]])


In [12]:
y.add_(x) # 任何 以''_''结尾的操作都会用结果替换原变量. 例如: ''x.copy_(y)'', ''x.t_()'', 都会改变 ''x''.
print(y)

tensor([[1.3937, 1.4660, 1.7507],
        [0.3443, 1.3641, 0.1677],
        [0.3474, 1.7869, 0.7800],
        [0.9442, 1.2195, 1.1489],
        [1.3853, 0.3768, 1.0244]])


In [13]:
print(x[:,1])

tensor([0.4841, 0.6409, 0.9291, 0.9322, 0.2530])


In [14]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # size -1从其他维度判断
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
x = torch.randn(1) # 当只有一个元素的张量，使用.item()来得到Python数据类型的数值
print(x)
print(x.item())

tensor([0.8665])
0.866524338722229


In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [20]:
torch.__version__

'1.5.0'

In [21]:
x = torch.rand(2,3)
x

tensor([[0.0700, 0.9067, 0.1963],
        [0.1217, 0.8147, 0.8024]])

In [22]:
print(x.shape)
print(x.size())

torch.Size([2, 3])
torch.Size([2, 3])


In [23]:
y = torch.rand(2,3,4,5)
print(y.size())
y

torch.Size([2, 3, 4, 5])


tensor([[[[0.4196, 0.9608, 0.8608, 0.1116, 0.4441],
          [0.9725, 0.6679, 0.2532, 0.0416, 0.3769],
          [0.8974, 0.2688, 0.9459, 0.4468, 0.7623],
          [0.4100, 0.6412, 0.6577, 0.3703, 0.5714]],

         [[0.0892, 0.3743, 0.2879, 0.2085, 0.7645],
          [0.1930, 0.2197, 0.3478, 0.1762, 0.9000],
          [0.1650, 0.4572, 0.2952, 0.4274, 0.2783],
          [0.6142, 0.0382, 0.4316, 0.2742, 0.3421]],

         [[0.5913, 0.9655, 0.7055, 0.2034, 0.8030],
          [0.6236, 0.2264, 0.7528, 0.5042, 0.7444],
          [0.4024, 0.7472, 0.3869, 0.2280, 0.8184],
          [0.9903, 0.3110, 0.9649, 0.5377, 0.8193]]],


        [[[0.1055, 0.7091, 0.8165, 0.5146, 0.2331],
          [0.8199, 0.3458, 0.2433, 0.0246, 0.5659],
          [0.4701, 0.4550, 0.4949, 0.1705, 0.4071],
          [0.1316, 0.6270, 0.1882, 0.0146, 0.0988]],

         [[0.1671, 0.2032, 0.5759, 0.0534, 0.5412],
          [0.4616, 0.0453, 0.3553, 0.6853, 0.4111],
          [0.1355, 0.8016, 0.3395, 0.0737, 0.6976],
  

在同构的意义下，第零阶张量（r = 0）为标量（Scalar），第一阶张量（r = 1）为向量（Vector），第二阶张量（r = 2）则成为矩阵 （Matrix），第三阶以上的统称为多维张量。

In [24]:
scalar = torch.tensor(3.1433223)
print(scalar)
scalar.size()

tensor(3.1433)


torch.Size([])

In [25]:
scalar.item()

3.143322229385376

In [26]:
tensor = torch.tensor([3.1433223])
print(tensor)
tensor.size()

tensor([3.1433])


torch.Size([1])

In [27]:
tensor.item()

3.143322229385376

In [28]:
long = tensor.long()
long

tensor([3])

In [29]:
half = tensor.half()
half

tensor([3.1426], dtype=torch.float16)

In [31]:
int_t = tensor.int()
int_t

tensor([3], dtype=torch.int32)

In [32]:
flo = tensor.float()
flo

tensor([3.1433])

In [33]:
short = tensor.short()
short

tensor([3], dtype=torch.int16)

In [34]:
ch = tensor.char()
ch

tensor([3], dtype=torch.int8)

In [35]:
bt = tensor.byte()
bt

tensor([3], dtype=torch.uint8)

In [36]:
a = torch.randn((3,2))
numpy_a = a.numpy()
print(numpy_a)

[[-1.4845893  -0.5949944 ]
 [ 0.8293027   1.162848  ]
 [-0.01354974 -0.4272115 ]]


In [37]:
torch_a = torch.from_numpy(numpy_a)
torch_a

tensor([[-1.4846, -0.5950],
        [ 0.8293,  1.1628],
        [-0.0135, -0.4272]])

In [41]:
rnd = torch.rand(5,3)
rnd

tensor([[0.5286, 0.3967, 0.0967],
        [0.1848, 0.1653, 0.1768],
        [0.3916, 0.0010, 0.5113],
        [0.4688, 0.6514, 0.4383],
        [0.9932, 0.1616, 0.6402]])

In [42]:
one = torch.ones(2,2)
one

tensor([[1., 1.],
        [1., 1.]])

In [43]:
zero = torch.zeros(2,2)
zero

tensor([[0., 0.],
        [0., 0.]])

In [44]:
eye = torch.eye(2,2)
eye

tensor([[1., 0.],
        [0., 1.]])

In [45]:
x = torch.randn(3,3)
print(x)

tensor([[-0.6300, -1.4287, -0.8907],
        [-0.5481,  0.7135,  0.3691],
        [ 2.0259, -2.7716,  0.7707]])


In [46]:
max_value,max_idx = torch.max(x,dim=1)
print(max_value,max_idx)
# 沿着行取最大值

tensor([-0.6300,  0.7135,  2.0259]) tensor([0, 1, 0])


In [47]:
sum_x = torch.sum(x,dim=1)
print(sum_x)

tensor([-2.9495,  0.5345,  0.0249])


In [49]:
y = torch.randn(3,3)
z = x + y
print(z)

tensor([[-0.2565, -0.4785, -1.3095],
        [ 0.5088,  0.1053,  1.4266],
        [ 1.8071, -3.3194,  0.4359]])


In [50]:
# 以_为结尾的，均会改变调用值
x.add_(x)
print(x)

tensor([[-1.2600, -2.8575, -1.7814],
        [-1.0963,  1.4270,  0.7382],
        [ 4.0517, -5.5432,  1.5413]])
