In [1]:
import torch
import torch.nn as nn
torch.__version__

'1.5.0'

In [2]:
import torch.nn.functional as F

In [3]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.conv1 = nn.Conv2d(1,6,3)
        self.fc1 = nn.Linear(1350,10)
    def forward(self,x):
        print(x.size())
        x = self.conv1(x)
        x = F.relu(x)
        print(x.size())
        x = F.max_pool2d(x,(2,2))
        x = F.relu(x)
        print(x.size())
        x = x.view(x.size()[0],-1)
        print(x.size())
        x = self.fc1(x)
        return x
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=1350, out_features=10, bias=True)
)


In [4]:
for parameters in net.parameters():
    print(parameters)

Parameter containing:
tensor([[[[-0.3019,  0.1001,  0.1437],
          [ 0.0494, -0.1227, -0.1368],
          [ 0.1253, -0.0367,  0.1636]]],


        [[[ 0.0243,  0.0253,  0.1578],
          [-0.0865,  0.3138,  0.2121],
          [ 0.2625, -0.3271,  0.0662]]],


        [[[ 0.0935,  0.1056, -0.1395],
          [ 0.1236, -0.1010, -0.0960],
          [-0.1251,  0.2068,  0.2601]]],


        [[[ 0.2582, -0.0221,  0.1689],
          [ 0.0855,  0.1008,  0.1835],
          [-0.0018,  0.0223,  0.0614]]],


        [[[-0.2871,  0.1613, -0.0661],
          [-0.0589,  0.1081,  0.1263],
          [ 0.0395, -0.2725,  0.0854]]],


        [[[ 0.0802, -0.2292, -0.0601],
          [ 0.0189,  0.0502,  0.0823],
          [ 0.3142, -0.1817,  0.3178]]]], requires_grad=True)
Parameter containing:
tensor([-0.2154,  0.1962,  0.1346,  0.2328,  0.2971,  0.1559],
       requires_grad=True)
Parameter containing:
tensor([[ 1.2504e-02,  1.7202e-02, -5.3985e-03,  ..., -2.2400e-02,
         -1.5247e-02, -8.5363e-0

In [6]:
for name,parameters in net.named_parameters():
    print(name,':',parameters.size())

conv1.weight : torch.Size([6, 1, 3, 3])
conv1.bias : torch.Size([6])
fc1.weight : torch.Size([10, 1350])
fc1.bias : torch.Size([10])


In [7]:
input = torch.randn(1,1,32,32)
out = net(input)
out.size()

torch.Size([1, 1, 32, 32])
torch.Size([1, 6, 30, 30])
torch.Size([1, 6, 15, 15])
torch.Size([1, 1350])


torch.Size([1, 10])

In [8]:
input.size()

torch.Size([1, 1, 32, 32])

In [9]:
# 在反向传播前，先要将所有参数的梯度清零
net.zero_grad()
out.backward(torch.ones(1,10))

In [10]:
y = torch.arange(0,10).view(1,10).float()
criterion = nn.MSELoss()
loss = criterion(out,y)
print(loss.item())

28.951562881469727


In [11]:
import torch.optim

In [12]:
out = net(input)
criterion = nn.MSELoss()
loss = criterion(out,y)
optimizer = torch.optim.SGD(net.parameters(),lr = 0.01)
optimizer.zero_grad()
loss.backward()
optimizer.step()

torch.Size([1, 1, 32, 32])
torch.Size([1, 6, 30, 30])
torch.Size([1, 6, 15, 15])
torch.Size([1, 1350])
